- README.md
- lib/generators/qbwc/install/templates/db/migrate/create_qbwc_jobs.rb
- lib/qbwc.rb
- lib/qbwc/active_record/job.rb
- lib/qbwc/job.rb
- test/qbwc/integration/request_generation_test.rb
The original qbwc gem supported passing optional requests to QBWC.add_job. This pull request restores a mostly similar functionality, primarily for backwards compatibility. Addresses #36.
Revision of https://github.com/skryl/qbwc/pull/38
> Permit passing optional requests when adding a job (REVISED)

- README.md
- lib/qbwc.rb
- lib/qbwc/active_record/job.rb
- lib/qbwc/active_record/session.rb
- lib/qbwc/job.rb
- lib/qbwc/worker.rb
- spec/qbwc/session_spec.rb
- test/qbwc/integration/job_management_test.rb
- test/qbwc/integration/request_generation_test.rb
- test/test_helper.rb
Allow a job to delete itself after completion (as discussed [here](https://github.com/skryl/qbwc#creating-jobs)). This introduces a new required parameter for handle_response in order to access the current job:
> Add QBWC.delete_job

- README.md
- lib/generators/qbwc/install/templates/db/migrate/create_qbwc_jobs.rb
- lib/qbwc.rb
- lib/qbwc/active_record/job.rb
- lib/qbwc/job.rb
- lib/qbwc/worker.rb
- test/qbwc/integration/job_management_test.rb
- test/qbwc/integration/request_generation_test.rb
This allows passing arbitrary data to handle_response, in order to access model attributes when handling responses (analogous to #36 for responses). This introduces a new optional parameter for handle_response.
> Permit passing optional data for response handling

- README.md
- lib/generators/qbwc/install/templates/config/qbwc.rb
- lib/qbwc.rb
- lib/qbwc/controller.rb
- test/qbwc/controllers/controller_test.rb
- test/test_helper.rb
This creates new function `set_session_initializer` to perform arbitrary processing at the beginning of each QuickBooks Web Connector session.
> Allow specifying arbitrary code to be executed at the start of each session

- lib/qbwc/session.rb
- test/qbwc/integration/session_test.rb
- test/test_helper.rb
This primarily fixes an issue with session.progress not updating properly when passing requests into add_job. Two new test cases were added; one for passing requests, and one for worker requests.
As a bonus, this also contains these items that seemed convenient to address at the same time:
* Improve calculation of session.progress as a percentage of jobs completed
* DRY code maintenance of existing session tests
> Fix session progress when passing requests

- README.md
- lib/qbwc/job.rb
- lib/qbwc/session.rb
- lib/qbwc/worker.rb
- test/qbwc/integration/job_management_test.rb
- test/qbwc/integration/request_generation_test.rb
- test/qbwc/integration/response_test.rb
This expands testing of session progress when encountering errors and warns. This could stand a thorough review and exercise since it revises (but cleans up?) the flow of control when processing responses.
This is a branch of another branch feature/request_status_values.
> Session progress during error conditions

- lib/qbwc/controller.rb
- lib/qbwc/session.rb
- test/qbwc/controllers/controller_test.rb
- test/qbwc/integration/response_test.rb
- test/test_helper.rb
Certain errors received from QuickBooks have an alternate format (blank response, hresult code, and error message, as shown in [this example](https://github.com/rchekaluk/qbwc/blob/bugfix/issue53/test/test_helper.rb#L176-181)).
When `on_error = :continue`, to prevent a looping condition where QuickBooks continues to issue `send_request` infinitely, the gem must return an appropriate progress value that eventually reaches 100 (a value of 100 informs QuickBooks that the session is finished).
This change passes these alternately-formatted errors into the gem's normal response processing, which subsequently triggers the normal calculation of progress value.
Fixes #53.
> Handle alternate error format

- lib/qbwc/controller.rb
- test/qbwc/controllers/controller_test.rb
For completeness, this small adjustment to https://github.com/skryl/qbwc/pull/57 assigns `session.status_severity` to `'Error'` for alternate-format errors. Note that alternate-format errors don't contain a status_severity per se, so this assignment overloads the field with a placeholder value.
This change has only minor impacts:
* [`response_is_error?`](https://github.com/skryl/qbwc/blob/master/lib/qbwc/session.rb#L27-29
) is more accurate
* The application's `handle_response` will be able to access a proper value for `session.status_severity`
> Assign status_severity for alternate-format errors

- test/qbwc/integration/routes_test.rb
- test/test_helper.rb
The failing `RoutesTest#test_qbwc/action_without_soap_returns_successfully` fails with `ActionView::MissingTemplate` exactly like #55, apparently due to an uninitialized Rails application environment. This pull request initializes the application in RoutesTest, thereby allowing the test to succeed.
> Fix failing RoutesTest

- lib/generators/qbwc/install/templates/config/qbwc.rb
- lib/qbwc.rb
- lib/qbwc/controller.rb
- lib/qbwc/job.rb
- lib/qbwc/session.rb
- test/qbwc/controllers/controller_test.rb
- test/qbwc/integration/response_test.rb
- test/qbwc/integration/session_test.rb
- test/test_helper.rb
Adds new config parameter log_sensitive_lines (default `false` on production, and `true` otherwise) that determines if request and response content is logged.
Emits a log entry at each send_request operation that doesn't contain sensitive information (requires minor code restructuring).
Standardizes the format (string qbXML or hash) of logged requests and responses in this way:
* Internal requests: logged in the format in which they were provided (either string or hash)
* Requests sent to QuickBooks: logged as string qbXML
* Responses from QuickBooks: logged as string qbXML (this required a minor change)
> Allow suppressing sensitive log lines

- lib/qbwc/session.rb
- test/qbwc/integration/request_generation_test.rb
Fixes #58 by explicitly returning a value from session.reset.
I've also struggled with the flow of control in session.next_request; I'd spent a little time trying to clean it up but gave up in the interest of time (though IIRC, the minor improvement https://github.com/skryl/qbwc/commit/3fb48dafb145b2b5e58781949df8813363bfb1b8 fell out of that inquiry).
I concur about implicit returns; even though they are appealing to the functional programming purist, I typically try to explicitly `return` whenever possible.
> Fix issue 58

- lib/qbwc/job.rb
- test/qbwc/integration/request_generation_test.rb
Fixes a small bug where an individual string request is not converted into an array, thus mangling the request sent to QuickBooks.
> Fix individual string request not converted into array

- README.md
- lib/qbwc/controller.rb
- test/qbwc/controllers/controller_test.rb
I think page 36 of the following means the FileID should change when downloading a new file?
https://developer-static.intuit.com/qbSDK-current/doc/PDF/QBWC_proguide.pdf
> Generate file id on every download

- lib/generators/qbwc/install/templates/db/migrate/create_qbwc_sessions.rb
AFAICT there is no need for a limit on the size of column qbwc_sessions.pending_jobs. I suspect that the existing 1000-char limit may have been a quick-and-dirty technique to extend beyond a [Rails implicit limit of 255 chars](http://stackoverflow.com/questions/8694273/changing-a-column-type-to-longer-strings-in-rails/8694483#8694483). Fixes #75.
References:
* http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column
* http://www.wetware.co.nz/2009/04/rails-migration-data-types-mysql-postgresql-sqlite/
> Relax 1000-char limit on qbwc_sessions.pending_jobs

- CHANGELOG.md
- README.md
- lib/generators/qbwc/install/install_generator.rb
- lib/generators/qbwc/install/templates/db/migrate/change_request_index.rb
- lib/generators/qbwc/install/templates/db/migrate/create_qbwc_jobs.rb
- lib/generators/qbwc/install/templates/db/migrate/index_qbwc_jobs.rb
- lib/qbwc.rb
- lib/qbwc/active_record/job.rb
- lib/qbwc/job.rb
- lib/qbwc/session.rb
- test/qbwc/integration/job_management_test.rb
- test/test_helper.rb
This PR provides various changes to ease the migration path from users already using a prior version of qbwc:
* Make session an optional argument, defaulting to `QBWC::Session.get`
* Separate out new migrations, allowing incremental changes to existing schema
* Draft instructions for migrating to this version
Other notes:
* You will want to bump major version when releasing, since this version includes breaking changes
* Rerunning `rails generate qbwc:install` is not fully idempotent
cc @bkroeker
> Courtesy changes to aid migration

- lib/qbwc/job.rb
This simple commit moves the debug logging in QBWC::Job#process_response (when QBWC.log_requests_and_responses is enabled) closer to the top of the method.  I found this useful when debugging the empty response issue (fixed in PR #89) because that bug was generating an exception in QBWC::Session#response= and the response was thus not getting logged.
Note that I wasn't sure how one would easily test the logging, so there's no associated test.
> Log qbxml_response closer to the top of #process_response

- README.md
One of the things I was initially confused by is that there appears to be an inconsistency in how request and response hashes are built --- whereas when sending a request, the top-level _rq tag is included as the top-level key (e.g. `customer_query_rq`), the corresponding response hash (as passed to `QBWC::Worker#handle_response`) does not include the _rs tag shown in the actual QBXML.
While I might classify that as a bug in the API, changing it would break existing code, so this PR at least clarifies the documentation by making explicit what was already implied in code example.
> Clarify documentation regarding top-level tag in response hash

- lib/qbwc/controller.rb
The following deprecation warnings appear in the development log after running the Web Connector:
```
DEPRECATION` WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in included at /home/webuser/.rvm/gems/ruby-2.3.1/bundler/gems/qbwc-e09e655b589c/lib/qbwc/controller.rb:12)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in included at /home/webuser/.rvm/gems/ruby-2.3.1/bundler/gems/qbwc-e09e655b589c/lib/qbwc/controller.rb:12)
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from block in included at /home/webuser/.rvm/gems/ruby-2.3.1/bundler/gems/qbwc-e09e655b589c/lib …
```
> Use around_action style callbacks in place of around_filter

- qbwc.gemspec
I can't find anything to indicate there's actually a dependency on rb-fsevent.  
It's an OSX-based library for FUSE events, I think it was added at one point to test with Guard, but Guard has long since been removed.
> remove unused dependency

- lib/qbwc/active_record/job.rb
closes #134 Updated uniqueness validation for name on QbwcJob to explicitly validate with `:case_sensitive => true` to fix rails 6 deprecation warning.
> Rails 6 uniqueness validator deprecation warning
